version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: GymHardcoreDB
    volumes:
      - ./log-directory:/var/lib/postgresql
    ports:
      - "5440:5432"
